# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader = "javafml"
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
# Forge for 1.14.4 is version 28
loaderVersion = "[28,)"
# A URL to refer people to when problems occur with this mod
issueTrackerURL = "https://github.com/snowshock35/jei-integration/issues"

[[mods]]
  modId = "jeiintegration"
  version = "${file.jarVersion}"
  displayName = "JEI Integration"
  displayURL = "https://curseforge.com/minecraft/mc-mods/jei-integration"
  updateJSONURL = "https://cdn.snowshock35.com/mods/jei-integration/update.json"
  logoFile = "logo.png"
  authors = "SnowShock35"
  credits = "Tonius for the original mod; NEI Integration."
  description = """
  JEI Integration, the successor to NEI Integration by
  Tonius, is an addon for Just Enough Items (JEI) for
  Minecraft 1.10 and above. The mod provides JEI
  recipe handlers for other mods where otherwise
  absent. In addition to additional recipe handlers,
  it adds configurable tooltips which can provide
  insightful information for pack developers and
  tech-savvy players."""

[[dependencies.jeiintegration]]
  modId="jei"
  mandatory=true
  versionRange="[6,)"
  ordering="NONE"
  side="BOTH"

[[dependencies.jeiintegration]]
  modId="forge"
  mandatory=true
  versionRange="[28,)"
  ordering="NONE"
  side="BOTH"

  [[dependencies.jeiintegration]]
  modId="minecraft"
  mandatory=true
  versionRange="[1.14.4]"
  ordering="NONE"
  side="BOTH"